# Generated by Django 4.2.13 on 2024-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='a',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
